### ISSUE TITLE
 docker-compose environment variables declaration

### ISSUE THREAD

**Issue by m4tm4t** [CatalysmsServerManager/7-days-to-die-server-manager#237]
It's more an improvement than feature

Docker-compose environment variables dosen't use .env at all.

The only var that correctly using .env is `NODE_ENV: ${NODE_ENV:-development}`

Instead of using 
```
  csmm-web:
    environment:
      NODE_ENV: ${NODE_ENV:-development}
      REDISSTRING: "redis://cache:6379"
      DBSTRING: "mysql2://csmm:mysecretpasswordissosecure@db:3306/csmm"
      CSMM_HOSTNAME: "http://localhost:30005"
      API_KEY_STEAM: ""
      DISCORDBOTTOKEN: ""
      DISCORDCLIENTSECRET: ""
      DISCORDCLIENTID: ""
      CSMM_ADMINS: ""
```
Make complete use of .env file : 
```
    environment:
      NODE_ENV: ${NODE_ENV:-development}
      REDISSTRING: ${REDISSTRING}
      DBSTRING: ${DBSTRING}
      CSMM_HOSTNAME: ${CSMM_HOSTNAME}
      API_KEY_STEAM: ${API_KEY_STEAM}
      DISCORDBOTTOKEN: ${DISCORDBOTTOKEN}
      DISCORDCLIENTSECRET: ${DISCORDCLIENTSECRET}
      DISCORDCLIENTID: ${DISCORDCLIENTID}
      CSMM_ADMINS: ${CSMM_ADMINS}
      CSMM_PORT: ${CSMM_PORT}
```

( same for the worker service )

`.env.example` file may need the two versions of REDISSTRING  & DBSTRING 

```
      # Classic env
     DBSTRING=mysql2://user:my-secret-pw@127.0.0.1:3306/csmm
     REDISSTRING=redis://127.0.0.1:6379
     
      # Docker env 
      # REDISSTRING: "redis://cache:6379"
      # DBSTRING: "mysql2://csmm:mysecretpasswordissosecure@db:3306/csmm"

```
